### ISSUE TITLE
Google Speech to text from Freeswitch/Asterisk

### ISSUE THREAD

**Issue by telecmi** [nikvaessen/nikvaessen.github.io#1]
Hi, 

 I hope its not place to ask this question ,But you have better understanding about Google speech API,SO that why i am asking this question,IS there any way i can integrate Google Speech API with SIP server like freeswitch. if yes can i know how can i do it Thanls

**Comment by nikvaessen** [comment]
I would say everything is possible with enough time ;). I however do not have any experience with SIP servers so I couldn't tell you how long it would take to implement such a feature. I can tell you that if you can intercept the audio packets going through the SIP server, it would be possible to send them to the Google API for processing. You could use [this API{](https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1#google.cloud.speech.v1.Speech.StreamingRecognize).
